Creating a GitHub Action to run automated test
Arduino-CI/arduino_ci pull request #200
Opened 2020-11-09 05:49 UTC by prestoncarman

## Issues Fixed

* Fixes#199

2020-11-09 06:10 UTC, prestoncarman commented
The GitHub Action ran on my forked repository, but it does not seems to have run on PR for Arduino CI. Are GitHub Actions turned on? I think they are on by default.

2020-11-09 06:12 UTC, jgfoster commented
@prestoncarman, I don't think it will run until it is part of the code being _merged into_. So, once this PR is accepted, then subsequent PRs will be tested.

2020-11-09 06:22 UTC, prestoncarman commented
Ah... this must be a security issue. This allows the repository owner to review the action before allowing it to run on their repository.

2020-11-10 14:42 UTC, ianfixes commented
Is this intended as a guide to how a library owner might set up Arduino CI as a GitHub action in their own repo?

2020-11-10 16:08 UTC, jgfoster commented
See the discussion in #199.

2020-11-10 17:55 UTC, prestoncarman commented
The PR includes documentation for a library owner who wants to use Arduino CI in a GitHub Action.

Also, the Arduino CI tests in this repository are running as a GitHub Action in Ubuntu. Its nice that these tests will run in a fork without any additional set up. Both Travis CI and Appveyor CI need to be configured on a third party site. Issue #199 shares more reasoning.

2020-11-10 19:59 UTC, ianfixes commented
I'm on board with this change, but not sure why the check isn't running.  According to the settings, this should be all set right?
<img width="1149" alt="Screen Shot 2020-11-10 at 2 58 29 PM" src="https://user-images.githubusercontent.com/583459/98727035-4e76a700-2365-11eb-8acd-2d6e128fdbfe.png">

2020-11-10 21:51 UTC, jgfoster commented
My observation (see [Keypad](https://github.com/Arduino-CI/Keypad/pulls?q=is%3Apr)) is that the Actions are not installed untill they have been accepted. There is a bit of a leap-of-faith, but you can go look at the Actions in the [source repository](https://github.com/prestoncarman/arduino_ci/actions) and have some confidence that they will behave the same when accepted to your repository.

2020-11-10 23:31 UTC, prestoncarman commented
After reading your comments about running in different OSes. I started looking into what GitHub Actions supports. This PR's GitHub Action now includes tests on Windows Server 2019, Ubuntu 18.04, and macOS Catalina 10.15. The version of macOS required updating the Arduino IDE to the latest version. It was nice to see that the tests pass without any other changes.

2020-11-11 01:55 UTC, jgfoster commented
Running on macOS 10.15 will require addressing #155.

2020-11-11 04:46 UTC, prestoncarman commented
Also addresses #185.

2020-11-12 04:59 UTC, jgfoster commented
You can get macOS to pass now by explicitly downloading a more recent version of Arduino.app in your Action script. See what was [added to Blink](https://github.com/Arduino-CI/Blink/pull/6/commits/c3a819c163ac03dbba997a6f17c12c98b7dd7c31).

2020-11-13 21:38 UTC, ianfixes commented
I think this just needs some steps to reflect what was added in #180

2020-11-13 21:39 UTC, ianfixes commented
Also, this should contain a follow-up (if it can't be done already) to add the badges to the `README.md`

2020-11-14 03:11 UTC, ianfixes commented
This seems like it's missing an action for cleaning / resetting the workspace before each build
https://github.com/marketplace/actions/clean-workspace

I'm basing that off [this build](https://github.com/Open-Acidification/TankControllerLib/runs/1398445342?check_suite_focus=true#step:6:24) which is [configured similarly](https://github.com/Open-Acidification/TankControllerLib/blob/master/.github/workflows/Arduino-CI.yaml#L12) and produces the following surprise:

```
Using pre-existing library...                                      LiquidCrystal
Using pre-existing library...                                             RTClib
Using pre-existing library...                                     Adafruit_BusIO
Using pre-existing library...                                  Adafruit_MAX31865
```

This shouldn't happen; the test should start from a blank slate each time and install the libraries fresh.

2020-11-14 03:13 UTC, ianfixes commented
Deleted a comment that was incorrect.  

I think this is missing a workspace-cleanup step.

2020-11-14 07:22 UTC, per1234 commented
>add the badges to the README.md

Here's the Markdown for the badge:
```
[![Arduino CI](https://github.com/Arduino-CI/arduino_ci/workflows/Arduino%20CI/badge.svg)](https://github.com/Arduino-CI/arduino_ci/actions?workflow=Arduino+CI)
```

>I think this is missing a workspace-cleanup step

Each run on the GitHub hosted runners starts in a fresh environment. Each of the matrix items here:
```yaml
  runTest: 
    strategy:
      matrix:
        os: [windows, ubuntu, macos]
```
Is actually a separate job: `runTest (windows)`, `runTest (ubuntu)`, `runTest (macos)`

So, on a GitHub Actions hosted runner, the only time you would need to clean up is if a step in a job could be negatively effected by changes to the system made by a previous step. Normally, you would just put that in a separate job, if needed, passing files from one job to the other via workflow artifacts, or data via job outputs.

From the description of the `AutoModality/action-clean` action, as well as some of my own experiences, it seems that, on self-hosted runners, the environment can be left dirty from previous workflow runs. But you aren't using a self-hosted runner, so that is not relevant here.

2020-11-15 21:29 UTC, ianfixes commented
> Each run on the GitHub hosted runners starts in a fresh environment

Aah, OK.  That's good to know

> `os: [windows, ubuntu, macos]`

I definitely prefer having 3 separate badges (one per OS) surfaced in the README, even if it means 3 config files with roughly the same contents.  

As far as getting the actions running in the first place, I assume my settings are correct but I don't see them firing for this PR.  Does that mean they need to be in the master branch before they can start working?

<img width="1045" alt="Screen Shot 2020-11-15 at 4 17 16 PM" src="https://user-images.githubusercontent.com/583459/99197303-afd0b880-275f-11eb-81ab-d674e502dea3.png">

2020-11-15 21:47 UTC, jgfoster commented
> Does that mean they need to be in the master branch before they can start working?

Yes. If you want to see that they pass you can see that [here](https://github.com/prestoncarman/arduino_ci/actions).

2020-11-15 22:19 UTC, per1234 commented
>I definitely prefer having 3 separate badges (one per OS) surfaced in the README, even if it means 3 config files with roughly the same contents.

The badges created by GitHub Actions are per-workflow, not per-job, so it would require three workflow files to create three badges. I think there is probable a service to generate arbitrary badges which could be controlled by the job results in a single workflow though.

However, I see that prestoncarman has split the single workflow into a `linux` and a `windows` workflow since the last time I commented, so this could be done with the GitHub Actions-generated badges if a macOS version of the workflow was added

2020-11-15 22:24 UTC, per1234 requested changes

2020-11-15 22:24 UTC, per1234 commented on README.md
> +**GitHub Actions** | [![Arduino CI](https://github.com/Arduino-CI/arduino_ci/workflows/linux/badge.svg)](https://github.com/Arduino-CI/arduino_ci/actions?workflow=linux) | | [![Arduino CI](https://gi
```suggestion
**GitHub Actions** | [![Arduino CI](https://github.com/Arduino-CI/arduino_ci/workflows/linux/badge.svg)](https://github.com/Arduino-CI/arduino_ci/actions?workflow=linux) | | [![Arduino CI](https://github.com/Arduino-CI/arduino_ci/workflows/windows/badge.svg)](https://github.com/Arduino-CI/arduino_ci/actions?workflow=windows)
```

2020-11-15 22:47 UTC, jgfoster commented
Good catch on the typo. As to `macOS`, it will fail until we get #155 and/or #185. GitHub Actions use 10.15, which fails. Of course, maybe the failing badge would be

2020-11-15 22:54 UTC, per1234 commented
>maybe the failing badge would be an indication that macOS doesn't work completely, which could be useful information!

This is my philosophy when setting up CI. The purpose of the check is to report any problems that might exist with the project, which means that a legitimate CI setup may result in a ❌ status. After that, work can be done on the project to try to get that lovely ✔️!

2020-11-15 23:00 UTC, prestoncarman commented on README.md
> +**GitHub Actions** | [![Arduino CI](https://github.com/Arduino-CI/arduino_ci/workflows/linux/badge.svg)](https://github.com/Arduino-CI/arduino_ci/actions?workflow=linux) | | [![Arduino CI](https://gi
Nice catch.

2020-11-16 00:14 UTC, ianfixes commented
Oh wow, I posted the same screenshot twice 🤦 
apologies.

2020-11-16 03:17 UTC, prestoncarman commented
A few notes about this change:

* GitHub Actions have been set up for Windows and Linux.
* Badges have been added to the README for these two actions.
* The README has a GitHub Actions example for a library creator.
* Removed deprecated TravisCI option `sudo: false`.
* Each workflow has two jobs: rubocop, TestSomething, and Network. These have been separated out ensure each has a clean environment. (related to #180) Also to allow parallel execurtion.

The change is ready for a final review.

_Side Note:_ It would be easy to add a workflow for macOS, but at this time I left that workflow out to allow all tests to pass. It seemed like moving to a new Arduino IDE version may be a significant change which is required for macOS (related to #185).

2020-11-17 04:57 UTC, per1234 approved these changes
Thanks @prestoncarman!

2020-11-29 02:02 UTC, ianfixes commented
I'm switching the base on this to the TDD branch to combine it with the `macos` action, and from there we'll track it on #226

2020-11-29 02:24 UTC, closed without merging